"""
100 benchmark queries for Amazon Reviews appliance dataset.
Designed to expose differences between dense and late interaction search.
"""

QUERIES = [
    # === NEGATION QUERIES (20) - dense embeddings struggle with "not/no/without" ===
    "ice maker that doesn't leak water on counter",
    "water filter that removes bad taste but keeps minerals",
    "dishwasher that doesn't leave white spots on glasses",
    "range hood that doesn't let cold air in during winter",
    "refrigerator that doesn't make loud humming noise at night",
    "freezer that doesn't frost up and need manual defrosting",
    "microwave that doesn't have a loud beep you can't turn off",
    "blender that doesn't leak from the bottom seal",
    "coffee maker that doesn't drip after pouring",
    "toaster that doesn't burn edges while leaving center underdone",
    "vacuum that doesn't lose suction over time",
    "air purifier that doesn't produce ozone smell",
    "dehumidifier that doesn't make the room too cold",
    "space heater that doesn't trip the circuit breaker",
    "fan that doesn't wobble or make clicking sounds",
    "washing machine that doesn't vibrate during spin cycle",
    "dryer that doesn't shrink clothes on normal setting",
    "garbage disposal that doesn't jam easily",
    "water heater that doesn't run out of hot water quickly",
    "air conditioner that doesn't drip water inside",

    # === CONTRADICTORY REQUIREMENTS (20) - dense averages these into mush ===
    "range hood powerful suction but quiet operation",
    "dishwasher compact size but large capacity inside",
    "ice maker makes ice fast but doesn't use much electricity",
    "blender powerful motor but lightweight and portable",
    "vacuum strong suction but easy to push on carpet",
    "air purifier covers large room but small footprint",
    "coffee maker brews fast but keeps coffee hot for hours",
    "toaster oven large capacity but heats up quickly",
    "microwave high wattage but energy efficient",
    "refrigerator spacious inside but slim profile for small kitchen",
    "freezer chest style capacity but upright convenience",
    "washing machine large drum but uses less water",
    "dryer fast drying but gentle on delicate fabrics",
    "fan powerful airflow but whisper quiet at night",
    "space heater heats room fast but stays cool to touch",
    "dehumidifier removes lots of moisture but quiet for bedroom",
    "air conditioner cools fast but low electricity bill",
    "water filter removes contaminants but fast flow rate",
    "garbage disposal powerful grind but quiet operation",
    "food processor powerful but easy to clean",

    # === MULTIPLE SPECIFIC KEYWORDS (20) - all must be present ===
    "countertop portable ice maker for RV camping road trip",
    "Samsung french door refrigerator water filter replacement",
    "dishwasher quiet operation cleans well dries dishes completely",
    "Whirlpool top load washer agitator heavy duty",
    "LG front load dryer steam refresh wrinkle free",
    "Vitamix blender smoothie ice crush professional grade",
    "Keurig coffee maker single serve pod reusable filter",
    "Instant Pot pressure cooker slow cooker air fryer combo",
    "Ninja blender food processor single serve cups",
    "KitchenAid stand mixer bread dough pasta attachment",
    "Breville espresso machine built in grinder milk frother",
    "Cuisinart food processor slicing shredding disc",
    "Dyson cordless vacuum hardwood floors pet hair",
    "Roomba robot vacuum self emptying smart mapping",
    "Shark steam mop hardwood laminate tile floors",
    "Honeywell air purifier HEPA filter large room allergies",
    "Frigidaire window air conditioner 8000 BTU remote control",
    "De'Longhi portable air conditioner no window vent hose",
    "GE Profile refrigerator ice maker water dispenser",
    "Bosch dishwasher third rack stainless steel tub",

    # === SPECIFIC PRODUCT REFERENCES (15) ===
    "nugget ice maker like sonic or chick-fil-a ice",
    "clear ice cubes not cloudy white ice for cocktails",
    "coffee maker that makes coffee like Starbucks drip",
    "blender that can make Jamba Juice style smoothies",
    "ice cream maker like Dairy Queen soft serve",
    "air fryer that makes food crispy like deep fried",
    "toaster that makes bagels crispy outside soft inside",
    "rice cooker that makes sushi rice perfectly sticky",
    "bread maker that makes artisan crusty loaves",
    "waffle maker that makes Belgian style deep pockets",
    "popcorn maker that makes movie theater style popcorn",
    "pizza oven that makes Neapolitan wood fired style pizza",
    "espresso machine that makes crema like Italian cafe",
    "meat grinder that handles venison and game meat",
    "food dehydrator for making beef jerky like store bought",

    # === LONGER DETAILED QUERIES (15) ===
    "looking for a portable countertop dishwasher that works in small apartment without permanent installation hooks up to sink faucet",
    "need a water filter for refrigerator that removes chlorine taste and odor but is cheaper than the brand name filter",
    "want an ice maker that makes the good nugget ice like you get at sonic drive-in not the regular hollow bullet shaped cubes",
    "searching for a vacuum cleaner that works well on both hardwood floors and thick carpet without switching settings manually",
    "need a quiet bedroom fan that oscillates and has a remote control so I don't have to get out of bed",
    "looking for a space heater that is safe to leave on overnight and won't be a fire hazard",
    "want a coffee maker that grinds beans fresh and brews directly into a thermal carafe not a glass pot",
    "need an air purifier for someone with severe allergies that removes pollen dust and pet dander",
    "searching for a dehumidifier that can handle a damp basement and drains continuously through a hose",
    "looking for a chest freezer that is energy efficient and doesn't cost much to run all year",
    "want a washing machine that handles large comforters and bulky items without getting off balance",
    "need a microwave that is simple to use for elderly parent with just a few buttons not too complicated",
    "searching for a garbage disposal that can handle fibrous vegetables like celery and artichokes",
    "looking for a range hood that vents outside not recirculating and fits 30 inch range",
    "want a refrigerator with adjustable shelves that can fit tall bottles and wide platters",

    # === COMPARISON AND PREFERENCE QUERIES (10) ===
    "water filter better than Brita removes more contaminants",
    "vacuum cleaner comparable to Dyson but more affordable",
    "coffee maker as good as Chemex pour over but automatic",
    "blender alternative to Vitamix similar performance lower price",
    "air purifier equivalent to Molekule but without subscription",
    "robot vacuum as smart as Roomba j7 but cheaper",
    "stand mixer comparable to KitchenAid but lighter weight",
    "espresso machine like Breville Barista but easier to use",
    "food processor similar to Cuisinart but quieter motor",
    "pressure cooker like Instant Pot but with better sealing",
]

assert len(QUERIES) == 100, f"Expected 100 queries, got {len(QUERIES)}"
